# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Osebo // Activity Sheet
email: hi@osebo.co
description:
  This is an activity sheet. Quick updates on my design process, projects, workflow and random things that run through my mind
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://osebo.co" # the base hostname & protocol for your site
twitter_username: osebo_
github_username:  osebo

# Build settings
markdown: kramdown
future: true
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
